version: '3.4'

services: 
  db:
    container_name: js-tests-db
    image: postgres:12.7-alpine
    environment:
      POSTGRES_PASSWORD: js-tests
    ports:
      - '5432:5432'

  mock:
    container_name: js-tests-mock
    image: wiremock/wiremock:2.32.0
    ports:
      - '5433:8080'
    volumes:
      - ./Mocks:/home/wiremock/mappings
